Repository Revisadinho/Revisadinho, pull requests merged in 2021-11, with the labels that each got.

#72 increasing size of plus button
  Revisadinho/MaintanenceScene/Views/MaintenanceView.swift
Labels: enhancement

#76 fixing constraints and deleting prints
  Revisadinho.xcodeproj/project.pbxproj
  Revisadinho/LightsScene/Views/LightsView.swift
  Revisadinho/LightsScene/Views/ViewController/LightsViewController.swift
  Revisadinho/MaintanenceScene/Views/MaintenanceView.swift
  RevisadinhoTests/MaintenanceViewControllerTests.swift
Labels: bug

#78 Feature/infinite timeline
  Revisadinho.xcodeproj/project.pbxproj
  Revisadinho/AddMaintenceScene/ViewModels/AddMaintenceViewModel.swift
  Revisadinho/AddMaintenceScene/Views/AddMaintenceView.swift
  Revisadinho/AddMaintenceScene/Views/AddMaintenceViewController.swift
  Revisadinho/AddMaintenceScene/Views/BottomSheetView.swift
  Revisadinho/AddMaintenceScene/Views/BottomSheetViewController.swift
  Revisadinho/AddMaintenceScene/Views/CustomButton.swift
  Revisadinho/AddMaintenceScene/Views/CustomLabel.swift
  Revisadinho/AddMaintenceScene/Views/CustomTextField.swift
  Revisadinho/AddMaintenceScene/Views/ServicesCollectionViewCell.swift
  Revisadinho/Assets.xcassets/sectionMark.imageset/Contents.json
  Revisadinho/Assets.xcassets/sectionMark.imageset/Rectangle 199.png
  Revisadinho/Assets.xcassets/sectionMark.imageset/Rectangle 199@2x.png
  Revisadinho/Assets.xcassets/sectionMark.imageset/Rectangle 199@3x.png
  Revisadinho/Helpers/Extension/Color.swift
  Revisadinho/MaintanenceScene/Views/MaintenanceView.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaintenanceViewController.swift
Labels: enhancement

#83 Feature/data to infinite timeline
  Revisadinho/MaintanenceScene/ViewModel/MaintenanceViewModel.swift
  Revisadinho/MaintanenceScene/Views/MaintenanceView.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaintenanceViewController.swift
  Revisadinho/Model/Model.swift
Labels: enhancement

#84 Configuring cocoapods
  .gitignore
  .swiftlint.yml
  Podfile
  Podfile.lock
  Revisadinho.xcodeproj/project.pbxproj
  Revisadinho.xcodeproj/xcshareddata/xcschemes/Revisadinho.xcscheme
  Revisadinho.xcworkspace/contents.xcworkspacedata
  Revisadinho.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Revisadinho.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Revisadinho/AddMaintenceScene/Views/AddMaintenceViewController.swift
  Revisadinho/AddMaintenceScene/Views/BottomSheetView.swift
  Revisadinho/MaintanenceScene/Views/MaintenanceView.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/DateComponentController.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaintenanceViewController.swift
  Revisadinho/Service/NotificationService.swift
Labels: enhancement

#85 Feature/event kit
  Revisadinho.xcodeproj/project.pbxproj
  Revisadinho/AddMaintenceScene/Views/AddMaintenceViewController.swift
  Revisadinho/Info.plist
  Revisadinho/Service/EventKitService.swift
Labels: enhancement

#86 Feature/notifications
  Revisadinho/Delegates/AppDelegate.swift
  Revisadinho/Service/NotificationService.swift
Labels: enhancement

#87 Solving bugs and cleaning maintenance view controller
  Revisadinho.xcodeproj/project.pbxproj
  Revisadinho/AddMaintenceScene/Views/AddMaintenceView.swift
  Revisadinho/AddMaintenceScene/Views/CustomTextField.swift
  Revisadinho/Base.lproj/LaunchScreen.storyboard
  Revisadinho/LightsScene/Views/Cells/LightTableViewCell.swift
  Revisadinho/LightsScene/Views/LightsView.swift
  Revisadinho/MaintanenceScene/ViewModel/MaintenanceViewModel.swift
  Revisadinho/MaintanenceScene/Views/Cells/FilterCell.swift
  Revisadinho/MaintanenceScene/Views/Components/DateComponent.swift
  Revisadinho/MaintanenceScene/Views/Components/DateComponentController.swift
  Revisadinho/MaintanenceScene/Views/MaintenanceView.swift
  Revisadinho/MaintanenceScene/Views/ModalView.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaintenanceCollectionViewDelegate.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaintenanceTableViewDelegateHelper.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaintenanceViewController.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaitenanceTableViewDelegate.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/ModalViewController.swift
  Revisadinho/Model/DateModel.swift
  Revisadinho/TabBarController/TabBarController.swift
Labels: bug, enhancement

#89 Feature/filter funcionality
  Revisadinho.xcodeproj/project.pbxproj
  Revisadinho/AddMaintenceScene/ViewModels/AddMaintenceViewModel.swift
  Revisadinho/Delegates/AppDelegate.swift
  Revisadinho/Delegates/SceneDelegate.swift
  Revisadinho/Helpers/Extension/Labels.swift
  Revisadinho/LightsScene/Views/ViewController/LightsViewController.swift
  Revisadinho/MaintanenceScene/ViewModel/MaintenanceViewModel.swift
  Revisadinho/MaintanenceScene/Views/Cells/FilterCell.swift
  Revisadinho/MaintanenceScene/Views/Cells/PlaceholderCell.swift
  Revisadinho/MaintanenceScene/Views/MaintenanceView.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaintenanceCollectionViewDelegate.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaintenancePickerDelegate.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaintenanceTableViewDelegateHelper.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaintenanceViewController.swift
  Revisadinho/MaintanenceScene/Views/ViewControllers/MaitenanceTableViewDelegate.swift
  Revisadinho/Router/MainRouter.swift
  Revisadinho/Service/EventKitService.swift
  Revisadinho/Service/NotificationService.swift
Labels: enhancement

#95 Bugfix/layout placeholder
  Revisadinho/MaintanenceScene/Views/Cells/PlaceholderCell.swift
Labels: bug
